---
- name: Converge
  hosts: all
  become: true

  vars:
    php_enable_webserver: false
    phergie_user: root
    phergie_install_path: /root/phergie

  roles:
    - geerlingguy.git
    - geerlingguy.php
    - geerlingguy.phergie
